// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqXCLCj4qNi_yZm6cDIhUmf8apBDhACdY',
    appId: '1:388314917497:web:abffb109720bfa36a482a8',
    messagingSenderId: '388314917497',
    projectId: 'food-save-58179',
    authDomain: 'food-save-58179.firebaseapp.com',
    storageBucket: 'food-save-58179.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJikFGXkyA6cXsWNXP5Pj0rpNWgGLCwt0',
    appId: '1:388314917497:ios:ad3c0561563a31faa482a8',
    messagingSenderId: '388314917497',
    projectId: 'food-save-58179',
    storageBucket: 'food-save-58179.firebasestorage.app',
    iosBundleId: 'com.example.hackathonApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJikFGXkyA6cXsWNXP5Pj0rpNWgGLCwt0',
    appId: '1:388314917497:ios:ad3c0561563a31faa482a8',
    messagingSenderId: '388314917497',
    projectId: 'food-save-58179',
    storageBucket: 'food-save-58179.firebasestorage.app',
    iosBundleId: 'com.example.hackathonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqXCLCj4qNi_yZm6cDIhUmf8apBDhACdY',
    appId: '1:388314917497:web:d07c31e73d76a854a482a8',
    messagingSenderId: '388314917497',
    projectId: 'food-save-58179',
    authDomain: 'food-save-58179.firebaseapp.com',
    storageBucket: 'food-save-58179.firebasestorage.app',
  );
}
